version: '3'
services: 
  hub:
    image: selenium/hub:4.16
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:4.16
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file : .env
    shm_size: "2g"
  firefox:
    image: selenium/node-firefox:4.16
    depends_on:
      - hub
    deploy:
      replicas: 1
    env_file : .env
    shm_size: "2g"